mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    callSettersOnNulls: true
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: Tepia@123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.102.216/lijiang?useSSL=false&allowMultiQueries=true
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
